### ISSUE TITLE
How Do I Download Tracks / Albums

### ISSUE THREAD

**Issue by Rajeshsahoo12** [rizxyu/applemusic-core#1]
Hi,

As I have installed applemusic-core using **npm i applemusic-core** command from readme.

But after that how to use the script..? As, I am not much experienced in these.

Thanks

**Comment by MuhammadRestu999** [comment]
Hello, thank you for downloading our module. At this time, we have not implemented code to download albums/tracks, we will notify you when we add it.

**Comment by rizxyu** [comment]
You can use the one in readme.md. sorry, at this time there is no code for downloading the album, you can wait for the next version, thank you.

**Comment by Rajeshsahoo12** [comment]
> Hello, thank you for downloading our module. At this time, we have not implemented code to download albums/tracks, we will notify you when we add it.

Ohhhh okay

**Comment by Rajeshsahoo12** [comment]
> You can use the one in readme.md. sorry, at this time there is no code for downloading the album, you can wait for the next version, thank you.

I had gone through readme. But as I am not much familiar with programming env. So, was just asking when downloading tracks/albums are available.

Then what is the command to dowload the same..?

**Comment by rizxyu** [comment]
> > You can use the one in readme.md. sorry, at this time there is no code for downloading the album, you can wait for the next version, thank you.
> 
> I had gone through readme. But as I am not much familiar with programming env. So, was just asking when downloading tracks/albums are available.
> 
> Then what is the command to dowload the same..?

I don't know when it will support albums for sure, but we will update the album downloader code as soon as possible: D

The album support download function seems to be different, but just wait until we update. Thank You.

**Comment by Rajeshsahoo12** [comment]
> > > You can use the one in readme.md. sorry, at this time there is no code for downloading the album, you can wait for the next version, thank you.
> > 
> > 
> > I had gone through readme. But as I am not much familiar with programming env. So, was just asking when downloading tracks/albums are available.
> > Then what is the command to dowload the same..?
> 
> I don't know when it will support albums for sure, but we will update the album downloader code as soon as possible: D
> 
> The album support download function seems to be different, but just wait until we update. Thank You.

Okay thanks

**Comment by rizxyu** [comment]
> > > > You can use the one in readme.md. sorry, at this time there is no code for downloading the album, you can wait for the next version, thank you.
> > > 
> > > 
> > > I had gone through readme. But as I am not much familiar with programming env. So, was just asking when downloading tracks/albums are available.
> > > Then what is the command to dowload the same..?
> > 
> > 
> > I don't know when it will support albums for sure, but we will update the album downloader code as soon as possible: D
> > The album support download function seems to be different, but just wait until we update. Thank You.
> 
> Okay thanks

Hellow, You can now download the album/playlist
u can PR if find a bug and want to fix it.
`https://github.com/rizxyu/applemusic-core/blob/main/lib/index.js`

**Comment by rizxyu** [comment]
Has added album/playlist

**Comment by Rajeshsahoo12** [comment]
> > > > > You can use the one in readme.md. sorry, at this time there is no code for downloading the album, you can wait for the next version, thank you.
> > > > 
> > > > 
> > > > I had gone through readme. But as I am not much familiar with programming env. So, was just asking when downloading tracks/albums are available.
> > > > Then what is the command to dowload the same..?
> > > 
> > > 
> > > I don't know when it will support albums for sure, but we will update the album downloader code as soon as possible: D
> > > The album support download function seems to be different, but just wait until we update. Thank You.
> > 
> > 
> > Okay thanks
> 
> Hellow, You can now download the album/playlist u can PR if find a bug and want to fix it. `https://github.com/rizxyu/applemusic-core/blob/main/lib/index.js`

Here I have lissted my doubts :-

1st doubt :-

As I am not much experienced in coding. How to use the program..? Do, I need to write program myself to use this program..?


2nd doubt :-

What is the quality of tracks / albums / playlist which gets downloaded...?

**Comment by rizxyu** [comment]
I will answer your second question, the audio quality has been set to normal audio so you can't mess with it to get better quality.

**Comment by Rajeshsahoo12** [comment]
> I will answer your second question, the audio quality has been set to normal audio so you can't mess with it to get better quality.

Okay thanks for info

**Comment by MuhammadRestu999** [comment]
The feature has been added in version v1.1.0, thanks for waiting!
@Rajeshsahoo12
