### ISSUE TITLE
Suggestion: Search Links

### ISSUE THREAD

**Issue by MaitreGEEK** [rizxyu/applemusic-core#2]
Hey, could it be possible to search for link without downloading it ?

I mean doing a download method on a URL that only return the title and artist informations and not the buffer.

Thanks !

**Comment by MaitreGEEK** [comment]
I know, the problem is that if you search from URL as a query you don't get informations on the title. And if I use the download functions with the URL I have the informations I need but I get the buffer with it and it makes my request bigger for only getting the title or the songs of a playlist or track.

**Comment by rizxyu** [comment]
you can do Pr

**Comment by MaitreGEEK** [comment]
No problem you can add it. Thanks for your research on the api of apple music. May I ask you something, is the fabdl API working with others sources and how did you find the processus for apple music ?

**Comment by rizxyu** [comment]
I don't know if the fabdl API can be used for other sources. And We did an inspect on several Apple Music song downloaders

**Comment by rizxyu** [comment]
Thank you for your input, we have updated the module, you can install it using

```bash
$ npm i github:rizxyu/applemusic-core
```
Example use:
```js
const { getInfo } = require("applemusic-core") /* To get only metadata "getInfo"*/

async function metadata(url) {
const result = await getInfo(url)
return result
}
metadata("https://example.com/)
```
